export const types = {
    FETCH_POST_ASYNC : 'FETCH_POST_ASYNC',
    CREATE_POST_ASYNC : 'CREATE_POST_ASYNC',
    FILL_POSTS : 'FILL_POSTS',
    FILL_NEW_POST : 'FILL_NEW_POST',
    CLEAR_POSTS: 'CLEAR_POSTS',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
    REMOVE_POST: 'REMOVE_POST',
    LIKE_POST: 'LIKE_POST',
    LIKE_POST_ASYNC: 'LIKE_POST_ASYNC',
    UNLIKE_POST: 'UNLIKE_POST',
    UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
};
