export const types = {
    AUTHENTICATE: 'AUTHENTICATE',
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    SIGNUP_ASYNC: 'SIGNUP_ASYNC',
    LOGIN_ASYNC: 'LOGIN_ASYNC',
    INITIALIZE: 'INITIALIZE',
    INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
    LOGOUT: 'LOGOUT',
    LOGOUT_ASYNC: 'LOGOUT_ASYNC',
}
